// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.31.0
// 	protoc        v4.25.1
// source: pb/svc/fixer/fixer.proto

package fixer

import (
	blob "github.com/aglide100/ai-test/pb/unit/blob"
	job "github.com/aglide100/ai-test/pb/unit/job"
	response "github.com/aglide100/ai-test/pb/unit/response"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MakingNewJobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth   *Auth    `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	IsWait bool     `protobuf:"varint,2,opt,name=isWait,proto3" json:"isWait,omitempty"`
	Job    *job.Job `protobuf:"bytes,3,opt,name=job,proto3" json:"job,omitempty"`
}

func (x *MakingNewJobReq) Reset() {
	*x = MakingNewJobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakingNewJobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakingNewJobReq) ProtoMessage() {}

func (x *MakingNewJobReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakingNewJobReq.ProtoReflect.Descriptor instead.
func (*MakingNewJobReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{0}
}

func (x *MakingNewJobReq) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *MakingNewJobReq) GetIsWait() bool {
	if x != nil {
		return x.IsWait
	}
	return false
}

func (x *MakingNewJobReq) GetJob() *job.Job {
	if x != nil {
		return x.Job
	}
	return nil
}

type MakingNewJobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res   *response.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	JobId string             `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
	Error *Error             `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *MakingNewJobRes) Reset() {
	*x = MakingNewJobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MakingNewJobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MakingNewJobRes) ProtoMessage() {}

func (x *MakingNewJobRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MakingNewJobRes.ProtoReflect.Descriptor instead.
func (*MakingNewJobRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{1}
}

func (x *MakingNewJobRes) GetRes() *response.Response {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *MakingNewJobRes) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

func (x *MakingNewJobRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type Auth struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Who   string `protobuf:"bytes,2,opt,name=who,proto3" json:"who,omitempty"`
}

func (x *Auth) Reset() {
	*x = Auth{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{2}
}

func (x *Auth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Auth) GetWho() string {
	if x != nil {
		return x.Who
	}
	return ""
}

type Error struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Msg string `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *Error) Reset() {
	*x = Error{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Error) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Error) ProtoMessage() {}

func (x *Error) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Error.ProtoReflect.Descriptor instead.
func (*Error) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{3}
}

func (x *Error) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type GetResultReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Auth  *Auth  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	JobId string `protobuf:"bytes,2,opt,name=jobId,proto3" json:"jobId,omitempty"`
}

func (x *GetResultReq) Reset() {
	*x = GetResultReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResultReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultReq) ProtoMessage() {}

func (x *GetResultReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultReq.ProtoReflect.Descriptor instead.
func (*GetResultReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{4}
}

func (x *GetResultReq) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *GetResultReq) GetJobId() string {
	if x != nil {
		return x.JobId
	}
	return ""
}

type GetResultRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res   *response.Response `protobuf:"bytes,1,opt,name=res,proto3" json:"res,omitempty"`
	Error *Error             `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
}

func (x *GetResultRes) Reset() {
	*x = GetResultRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetResultRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResultRes) ProtoMessage() {}

func (x *GetResultRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResultRes.ProtoReflect.Descriptor instead.
func (*GetResultRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{5}
}

func (x *GetResultRes) GetRes() *response.Response {
	if x != nil {
		return x.Res
	}
	return nil
}

func (x *GetResultRes) GetError() *Error {
	if x != nil {
		return x.Error
	}
	return nil
}

type CheckClientsReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CheckClientsReq) Reset() {
	*x = CheckClientsReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckClientsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckClientsReq) ProtoMessage() {}

func (x *CheckClientsReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckClientsReq.ProtoReflect.Descriptor instead.
func (*CheckClientsReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{6}
}

type CheckClientsRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Res []string `protobuf:"bytes,1,rep,name=res,proto3" json:"res,omitempty"`
}

func (x *CheckClientsRes) Reset() {
	*x = CheckClientsRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CheckClientsRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckClientsRes) ProtoMessage() {}

func (x *CheckClientsRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckClientsRes.ProtoReflect.Descriptor instead.
func (*CheckClientsRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{7}
}

func (x *CheckClientsRes) GetRes() []string {
	if x != nil {
		return x.Res
	}
	return nil
}

type GetBlobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Key   string `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
}

func (x *GetBlobReq) Reset() {
	*x = GetBlobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobReq) ProtoMessage() {}

func (x *GetBlobReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobReq.ProtoReflect.Descriptor instead.
func (*GetBlobReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{8}
}

func (x *GetBlobReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *GetBlobReq) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

type GetBlobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Blob *blob.Blob `protobuf:"bytes,1,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (x *GetBlobRes) Reset() {
	*x = GetBlobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBlobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRes) ProtoMessage() {}

func (x *GetBlobRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRes.ProtoReflect.Descriptor instead.
func (*GetBlobRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{9}
}

func (x *GetBlobRes) GetBlob() *blob.Blob {
	if x != nil {
		return x.Blob
	}
	return nil
}

type SendBlobReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Token string     `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	Blob  *blob.Blob `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (x *SendBlobReq) Reset() {
	*x = SendBlobReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBlobReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBlobReq) ProtoMessage() {}

func (x *SendBlobReq) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBlobReq.ProtoReflect.Descriptor instead.
func (*SendBlobReq) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{10}
}

func (x *SendBlobReq) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *SendBlobReq) GetBlob() *blob.Blob {
	if x != nil {
		return x.Blob
	}
	return nil
}

type SendBlobRes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BlobID string `protobuf:"bytes,1,opt,name=blobID,proto3" json:"blobID,omitempty"`
}

func (x *SendBlobRes) Reset() {
	*x = SendBlobRes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pb_svc_fixer_fixer_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendBlobRes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendBlobRes) ProtoMessage() {}

func (x *SendBlobRes) ProtoReflect() protoreflect.Message {
	mi := &file_pb_svc_fixer_fixer_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendBlobRes.ProtoReflect.Descriptor instead.
func (*SendBlobRes) Descriptor() ([]byte, []int) {
	return file_pb_svc_fixer_fixer_proto_rawDescGZIP(), []int{11}
}

func (x *SendBlobRes) GetBlobID() string {
	if x != nil {
		return x.BlobID
	}
	return ""
}

var File_pb_svc_fixer_fixer_proto protoreflect.FileDescriptor

var file_pb_svc_fixer_fixer_proto_rawDesc = []byte{
	0x0a, 0x18, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x66, 0x69, 0x78, 0x65, 0x72, 0x2f, 0x66,
	0x69, 0x78, 0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x15, 0x70, 0x62, 0x2f, 0x75,
	0x6e, 0x69, 0x74, 0x2f, 0x6a, 0x6f, 0x62, 0x2f, 0x6a, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x1a, 0x1f, 0x70, 0x62, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x2f, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x1a, 0x17, 0x70, 0x62, 0x2f, 0x75, 0x6e, 0x69, 0x74, 0x2f, 0x62, 0x6c, 0x6f, 0x62,
	0x2f, 0x62, 0x6c, 0x6f, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1f, 0x70, 0x62, 0x2f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x61, 0x0a, 0x0f,
	0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12,
	0x19, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x05, 0x2e,
	0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x73,
	0x57, 0x61, 0x69, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x06, 0x69, 0x73, 0x57, 0x61,
	0x69, 0x74, 0x12, 0x1b, 0x0a, 0x03, 0x6a, 0x6f, 0x62, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x09, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x4a, 0x6f, 0x62, 0x52, 0x03, 0x6a, 0x6f, 0x62, 0x22,
	0x67, 0x0a, 0x0f, 0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x52,
	0x65, 0x73, 0x12, 0x20, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x0e, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x52,
	0x03, 0x72, 0x65, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x22, 0x2e, 0x0a, 0x04, 0x41, 0x75, 0x74, 0x68,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x77, 0x68, 0x6f, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x77, 0x68, 0x6f, 0x22, 0x19, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x6d, 0x73, 0x67, 0x22, 0x3f, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x52, 0x65, 0x71, 0x12, 0x19, 0x0a, 0x04, 0x61, 0x75, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x05, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x04, 0x61, 0x75, 0x74, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x6a, 0x6f, 0x62, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x6a,
	0x6f, 0x62, 0x49, 0x64, 0x22, 0x4e, 0x0a, 0x0c, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x52, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x03, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0e, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x52, 0x03, 0x72, 0x65, 0x73, 0x12, 0x1c, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x06, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x52, 0x05, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x22, 0x11, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b, 0x43, 0x6c, 0x69,
	0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x22, 0x23, 0x0a, 0x0f, 0x43, 0x68, 0x65, 0x63, 0x6b,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x03, 0x72, 0x65, 0x73, 0x22, 0x34, 0x0a, 0x0a,
	0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f,
	0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x22, 0x2c, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73,
	0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a,
	0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x04, 0x62, 0x6c, 0x6f, 0x62,
	0x22, 0x43, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x12,
	0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x1e, 0x0a, 0x04, 0x62, 0x6c, 0x6f, 0x62, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x75, 0x6e, 0x69, 0x74, 0x2e, 0x42, 0x6c, 0x6f, 0x62, 0x52,
	0x04, 0x62, 0x6c, 0x6f, 0x62, 0x22, 0x25, 0x0a, 0x0b, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x62, 0x6c, 0x6f, 0x62, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x62, 0x6c, 0x6f, 0x62, 0x49, 0x44, 0x32, 0xe3, 0x02, 0x0a,
	0x0c, 0x46, 0x69, 0x78, 0x65, 0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x46, 0x0a,
	0x0c, 0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x12, 0x10, 0x2e,
	0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a,
	0x10, 0x2e, 0x4d, 0x61, 0x6b, 0x69, 0x6e, 0x67, 0x4e, 0x65, 0x77, 0x4a, 0x6f, 0x62, 0x52, 0x65,
	0x73, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0c, 0x3a, 0x01, 0x2a, 0x22, 0x07, 0x2f, 0x76,
	0x31, 0x2f, 0x6a, 0x6f, 0x62, 0x12, 0x40, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x12, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65,
	0x71, 0x1a, 0x0d, 0x2e, 0x47, 0x65, 0x74, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x73,
	0x22, 0x15, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0f, 0x3a, 0x01, 0x2a, 0x22, 0x0a, 0x2f, 0x76, 0x31,
	0x2f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x43, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x42, 0x6c,
	0x6f, 0x62, 0x12, 0x0b, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a,
	0x0b, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6c, 0x6f, 0x62, 0x52, 0x65, 0x73, 0x22, 0x1e, 0x82, 0xd3,
	0xe4, 0x93, 0x02, 0x18, 0x12, 0x16, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6c, 0x6f, 0x62, 0x2f, 0x7b,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x7d, 0x2f, 0x7b, 0x6b, 0x65, 0x79, 0x7d, 0x12, 0x3b, 0x0a, 0x08,
	0x53, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6f, 0x62, 0x12, 0x0c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42,
	0x6c, 0x6f, 0x62, 0x52, 0x65, 0x71, 0x1a, 0x0c, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x42, 0x6c, 0x6f,
	0x62, 0x52, 0x65, 0x73, 0x22, 0x13, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x3a, 0x01, 0x2a, 0x22,
	0x08, 0x2f, 0x76, 0x31, 0x2f, 0x62, 0x6c, 0x6f, 0x62, 0x12, 0x47, 0x0a, 0x0c, 0x43, 0x68, 0x65,
	0x63, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x12, 0x10, 0x2e, 0x43, 0x68, 0x65, 0x63,
	0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x71, 0x1a, 0x10, 0x2e, 0x43, 0x68,
	0x65, 0x63, 0x6b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x22, 0x13, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x0d, 0x12, 0x0b, 0x2f, 0x76, 0x31, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e,
	0x74, 0x73, 0x42, 0x2b, 0x5a, 0x29, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x67, 0x6c, 0x69, 0x64, 0x65, 0x31, 0x30, 0x30, 0x2f, 0x68, 0x61, 0x74, 0x65, 0x2d,
	0x61, 0x69, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x76, 0x63, 0x2f, 0x66, 0x69, 0x78, 0x65, 0x72, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pb_svc_fixer_fixer_proto_rawDescOnce sync.Once
	file_pb_svc_fixer_fixer_proto_rawDescData = file_pb_svc_fixer_fixer_proto_rawDesc
)

func file_pb_svc_fixer_fixer_proto_rawDescGZIP() []byte {
	file_pb_svc_fixer_fixer_proto_rawDescOnce.Do(func() {
		file_pb_svc_fixer_fixer_proto_rawDescData = protoimpl.X.CompressGZIP(file_pb_svc_fixer_fixer_proto_rawDescData)
	})
	return file_pb_svc_fixer_fixer_proto_rawDescData
}

var file_pb_svc_fixer_fixer_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_pb_svc_fixer_fixer_proto_goTypes = []interface{}{
	(*MakingNewJobReq)(nil),   // 0: MakingNewJobReq
	(*MakingNewJobRes)(nil),   // 1: MakingNewJobRes
	(*Auth)(nil),              // 2: Auth
	(*Error)(nil),             // 3: Error
	(*GetResultReq)(nil),      // 4: GetResultReq
	(*GetResultRes)(nil),      // 5: GetResultRes
	(*CheckClientsReq)(nil),   // 6: CheckClientsReq
	(*CheckClientsRes)(nil),   // 7: CheckClientsRes
	(*GetBlobReq)(nil),        // 8: GetBlobReq
	(*GetBlobRes)(nil),        // 9: GetBlobRes
	(*SendBlobReq)(nil),       // 10: SendBlobReq
	(*SendBlobRes)(nil),       // 11: SendBlobRes
	(*job.Job)(nil),           // 12: unit.Job
	(*response.Response)(nil), // 13: unit.Response
	(*blob.Blob)(nil),         // 14: unit.Blob
}
var file_pb_svc_fixer_fixer_proto_depIdxs = []int32{
	2,  // 0: MakingNewJobReq.auth:type_name -> Auth
	12, // 1: MakingNewJobReq.job:type_name -> unit.Job
	13, // 2: MakingNewJobRes.res:type_name -> unit.Response
	3,  // 3: MakingNewJobRes.error:type_name -> Error
	2,  // 4: GetResultReq.auth:type_name -> Auth
	13, // 5: GetResultRes.res:type_name -> unit.Response
	3,  // 6: GetResultRes.error:type_name -> Error
	14, // 7: GetBlobRes.blob:type_name -> unit.Blob
	14, // 8: SendBlobReq.blob:type_name -> unit.Blob
	0,  // 9: FixerService.MakingNewJob:input_type -> MakingNewJobReq
	4,  // 10: FixerService.GetResult:input_type -> GetResultReq
	8,  // 11: FixerService.GetBlob:input_type -> GetBlobReq
	10, // 12: FixerService.SendBlob:input_type -> SendBlobReq
	6,  // 13: FixerService.CheckClients:input_type -> CheckClientsReq
	1,  // 14: FixerService.MakingNewJob:output_type -> MakingNewJobRes
	5,  // 15: FixerService.GetResult:output_type -> GetResultRes
	9,  // 16: FixerService.GetBlob:output_type -> GetBlobRes
	11, // 17: FixerService.SendBlob:output_type -> SendBlobRes
	7,  // 18: FixerService.CheckClients:output_type -> CheckClientsRes
	14, // [14:19] is the sub-list for method output_type
	9,  // [9:14] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_pb_svc_fixer_fixer_proto_init() }
func file_pb_svc_fixer_fixer_proto_init() {
	if File_pb_svc_fixer_fixer_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pb_svc_fixer_fixer_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakingNewJobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MakingNewJobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Auth); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Error); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResultReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetResultRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckClientsReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CheckClientsRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBlobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBlobReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pb_svc_fixer_fixer_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendBlobRes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pb_svc_fixer_fixer_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pb_svc_fixer_fixer_proto_goTypes,
		DependencyIndexes: file_pb_svc_fixer_fixer_proto_depIdxs,
		MessageInfos:      file_pb_svc_fixer_fixer_proto_msgTypes,
	}.Build()
	File_pb_svc_fixer_fixer_proto = out.File
	file_pb_svc_fixer_fixer_proto_rawDesc = nil
	file_pb_svc_fixer_fixer_proto_goTypes = nil
	file_pb_svc_fixer_fixer_proto_depIdxs = nil
}
